### ISSUE TITLE
How to run migrations?

### ISSUE THREAD

**Issue by damianesteban** [maybachlabs/express-typescript-seed#6]
I think this is a great project structure and I would use sequelize-typescript in production applications except for the fact that there does not seem to be a simple way to handle migrations. Have you figured out how to run migrations when defining your models like this?

**Comment by kckolz** [comment]
Unfortunately no. That is something I would love to be able to do. If I was to start over I think I would use [typeorm](https://github.com/typeorm/typeorm) instead of Sequelize.

**Comment by damianesteban** [comment]
TypeORM is great, especially when used with [nestjs](https://github.com/nestjs/nest). Thanks for the info.
